### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by Renaud11232** [hashashin/OctoPrint-OpiTemp#8]
OctoPrint 1.4.0 now supports python 3 and plugins need to be updated to support it as well

## Expected Behavior

Plugin should be updated to support Python 3

## Current Behavior

Python 3 is not supported

## Possible Solution

In `__init__.py`, add :
```py
__plugin_pythoncompat__ = ">=2.7,<4"
```
In `opitemp.md` (in the Plugin Repository), under `compatibility:`, add `python: ">=2.7,<4"`. So it will look like this:
```yml
compatibility:

  octoprint:
  - 1.3.8

  os:
  - linux

  python: ">=2.7,<4"
```
